### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by sopedro** [shockwavemk/magento2-module-mail-smtp#6]
Not working in Magento 2.1.5, not install the module

**Comment by shockwavemk** [comment]
Hi, thank you for your feedback.
A more sophisticated error description would be helpful.
How did you try to install my module? Which kind of failure message did you get?

**Comment by sopedro** [comment]
Hi,

I installed normally, upload the files to server then bin/magento setup:upgrade bin/magento setup:di:compile bin/magento setup:static-content-deploy bin/magento indexer:reindex and clean all caches....no menu at all in backend, no errors, but can't use extension because theres no menu.
I installed your other extension for cron and works fine...

Thank you,

Pedro

**Comment by sopedro** [comment]
Hi, I installed the module using composer and now the module is installed, but no emails are sent.
Can you help?

Thanks

**Comment by shockwavemk** [comment]
Hi @sopedro,
yes, i can try to help you with my plug-in, but I need more information about the error.

On installation no additional menu is created in Magento2 backend.
Instead the existing one in "Stores > Configuration > Advanced > System > Mail Sending Settings" is enhanced. You have to change the settings there.

Did you select the connection type "smtp"?
Which type of authentication do you use?
Can you send me the correlating error/system log?

**Comment by sopedro** [comment]
Hi,

Sorry, my bad. I forget to change default magento email (sales@example.com) so, SES rejected the email, not your extension.

Your extension works very well and i like the way you add SMTP feature to Magento.

Thanks a lot.

A++

**Comment by shockwavemk** [comment]
I should add this point to the instructions. Thank you.
Best regards
M.
